use retailbilling;
INSERT INTO RETAILGENERALITEM(SHOPID, ITEMNAME, OWNER) VALUES (1, 'SILVER COIN', 'S');
INSERT INTO RETAILGENERALITEM(SHOPID, ITEMNAME, OWNER) VALUES (1, 'GOLD COIN', 'S');
INSERT INTO RETAILGENERALITEM(SHOPID, ITEMNAME, OWNER) VALUES (1, 'SILVER PEN', 'S');
INSERT INTO RETAILGENERALITEM(SHOPID, ITEMNAME, OWNER) VALUES (1, 'PEN', 'S'); 	