use retailbilling;
INSERT INTO SHOP(SHOPNAME,TINNUMBER) VALUES('Apna Jewellery', '10034142');
INSERT INTO USERINFORMATION(SHOPID, FIRSTNAME, LASTNAME, USERID, USERPASSWORD, ROLE) VALUES(1, 'Vivekanand', 'Lnu', 'admin', 'admin', 'ADMIN');
INSERT INTO USERINFORMATION(SHOPID, FIRSTNAME, LASTNAME, USERID, USERPASSWORD, ROLE) VALUES(1, 'Staff', 'Staff', 'staff', 'staff', 'STAFF');
INSERT INTO RETAILSTAFF(SHOPID, STAFFNAME) VALUES(1, 'STAFF');
INSERT INTO RETAILSTAFF(SHOPID, STAFFNAME) VALUES(1, 'OWNER'); 