#!/bin/sh

#

# tomcat        

#

# chkconfig: 

# description:  Start up the Tomcat servlet engine.

# Source function library.

RETVAL=$?
export JAVA_HOME=/software/jdk1.8.0_91
export PATH=$JAVA_HOME/bin:$PATH
CATALINA_HOME="/software/apache-tomcat-8.0.36"

case "$1" in

 start)

        if [ -f $CATALINA_HOME/bin/startup.sh ];

          then

   echo $"Starting Tomcat"

           $CATALINA_HOME/bin/startup.sh

        fi

;;

 stop)

        if [ -f $CATALINA_HOME/bin/shutdown.sh ];

          then

   echo $"Stopping Tomcat"

            $CATALINA_HOME/bin/shutdown.sh

        fi

  ;;

 *)

  echo $"Usage: $0 {start|stop}"

exit 1

;;

esac

exit $RETVAL