INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'BRACELET');
INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'JAL JUMKA');
INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'NOSEPIN');
INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'LOCKET SET');
INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'PATWASI');
INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'SETTING LADIES RING');
INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'SETTING GENTS RING');
INSERT INTO RETAILGOLDITEM(SHOPID, ITEMNAME) VALUES(1, 'EAR CHAIN');
