CREATE TABLE MORTGAGETRANSACTION(
	SHOPID SMALLINT UNSIGNED,
	TRANSID BIGINT UNSIGNED AUTO_INCREMENT,
	TRANSDATE DATETIME NOT NULL,
	TRANSENDDATE DATETIME NULL,
	KEEPERNAME VARCHAR(255) NULL,
	NOTES VARCHAR(2048),
	PERCENTAGE DECIMAL(12, 3) UNSIGNED NOT NULL,
	TOTALPRICE DECIMAL(12, 3) UNSIGNED NOT NULL,
	TRANSACTIONSTATUS ENUM('A', 'I') DEFAULT 'A' NOT NULL,
	TOTALGOLDWEIGHT   DECIMAL(9, 4) UNSIGNED,
	TOTALSILVERWEIGHT   DECIMAL(9, 4) UNSIGNED,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(TRANSID)
)ENGINE=InnoDB;

CREATE TABLE MORTGAGECUSTOMER(
	TRANSID BIGINT UNSIGNED,
	FIRSTNAME VARCHAR(255),
	LASTNAME  VARCHAR(255),
	CONTACTNUMBER VARCHAR(255),
	EMAILID VARCHAR(255),
	STREETADDRESS1 VARCHAR(512),
	STREETADDRESS2 VARCHAR(512),
	CITY VARCHAR(128),
	STATE VARCHAR(128),
	ZIPCODE VARCHAR(10),
	COUNTRY VARCHAR(64),
	FOREIGN KEY(TRANSID) REFERENCES MORTGAGETRANSACTION(TRANSID)ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE MORTGAGEGOLDITEMTRANSACTION(
	TRANSID BIGINT UNSIGNED,
	ITEMNAME VARCHAR(255) NOT NULL,
	QUANTITY INT UNSIGNED,
	PIECEPAIR VARCHAR(255),
	WEIGHT   DECIMAL(9, 4) UNSIGNED,
	FOREIGN KEY(TRANSID) REFERENCES MORTGAGETRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE MORTGAGESILVERITEMTRANSACTION(
	TRANSID BIGINT UNSIGNED,
	ITEMNAME VARCHAR(255) NOT NULL,
	QUANTITY INT UNSIGNED,
	PIECEPAIR VARCHAR(255),
	WEIGHT   DECIMAL(9, 4) UNSIGNED,
	FOREIGN KEY(TRANSID) REFERENCES MORTGAGETRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE MORTGAGEDIAMONDITEMTRANSACTION(
	TRANSID BIGINT UNSIGNED,
	ITEMNAME VARCHAR(255) NOT NULL,
	QUANTITY INT UNSIGNED,
	PIECEPAIR VARCHAR(255),
	GOLDWEIGHT   DECIMAL(9, 4) UNSIGNED,
	DIAMONDWEIGHT   DECIMAL(9, 4) UNSIGNED,
	FOREIGN KEY(TRANSID) REFERENCES MORTGAGETRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';


CREATE TABLE MORTGAGEGOLDITEM(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	ITEMNAME VARCHAR(255) NOT NULL,
	OWNER ENUM('S', 'U') DEFAULT 'S' NOT NULL,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, ITEMNAME)
)ENGINE='InnoDB';

CREATE TABLE MORTGAGEKEEPER(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	KEEPERNAME VARCHAR(255) NOT NULL,
	OWNER ENUM('S', 'U') DEFAULT 'S' NOT NULL,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, KEEPERNAME)
)ENGINE='InnoDB';