CREATE TABLE PURCHASERECORDTRANSACTION(
	SHOPID SMALLINT UNSIGNED,
	TRANSID BIGINT UNSIGNED AUTO_INCREMENT,
	TRANSDATE DATETIME NOT NULL,
	ITEMNAME VARCHAR(255) ,
	PARTYNAME VARCHAR(255) ,
	WEIGHT   DECIMAL(9, 4) UNSIGNED,
	CASHPAYMENT DECIMAL(12, 3) UNSIGNED,
	NOTES VARCHAR(2048) ,
	TRANSACTIONSTATUS ENUM('A', 'I') DEFAULT 'A' NOT NULL,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(TRANSID)
)ENGINE=InnoDB;

CREATE TABLE PURCHASEPAYMENT(
	TRANSID BIGINT UNSIGNED,
	AMOUNT DECIMAL(12, 3) UNSIGNED,
	REFERENCENUMBER VARCHAR(255) ,
	BANKNAME VARCHAR(255),
	PAYMENTTYPE VARCHAR(255),
	FOREIGN KEY(TRANSID)REFERENCES PURCHASERECORDTRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE=InnoDB;