CREATE TABLE SHOP (
	SHOPID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	SHOPNAME VARCHAR(255),
	TINNUMBER VARCHAR(255),
	UNIQUE(TINNUMBER),
	PRIMARY KEY(SHOPID)
)ENGINE=InnoDB;

CREATE TABLE USERINFORMATION (
	SHOPID SMALLINT UNSIGNED,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255)  NULL,
	USERID VARCHAR(255) NOT NULL,
	USERPASSWORD VARCHAR(255) NOT NULL,
	ROLE VARCHAR(255) NOT NULL,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, USERID)
)ENGINE=InnoDB;

CREATE TABLE RETAILTRANSACTION(
	SHOPID SMALLINT UNSIGNED,
	TRANSID BIGINT UNSIGNED AUTO_INCREMENT,
	TRANSDATE DATETIME NOT NULL,
	BILLTYPE ENUM('I', 'E') NOT NULL,
	DEALINGSTAFFNAME VARCHAR(255) DEFAULT 'STAFF' NOT NULL,
	NOTES VARCHAR(2048) ,
	INCLUDEPRICE ENUM('Y', 'N') DEFAULT 'Y' NOT NULL,
	TRANSACTIONSTATUS ENUM('A', 'I') DEFAULT 'A' NOT NULL,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(TRANSID)
)ENGINE=InnoDB;

CREATE TABLE RETAILCUSTOMER(
	TRANSID BIGINT UNSIGNED,
	FIRSTNAME VARCHAR(255),
	LASTNAME  VARCHAR(255),
	CONTACTNUMBER VARCHAR(255),
	EMAILID VARCHAR(255),
	STREETADDRESS1 VARCHAR(512),
	STREETADDRESS2 VARCHAR(512),
	CITY VARCHAR(128),
	STATE VARCHAR(128),
	ZIPCODE VARCHAR(10),
	COUNTRY VARCHAR(64),
	FOREIGN KEY(TRANSID) REFERENCES RETAILTRANSACTION(TRANSID)ON DELETE CASCADE
)ENGINE='InnoDB';


CREATE TABLE RETAILTAXINVOICE (
   SHOPID BIGINT UNSIGNED,
   TRANSID BIGINT UNSIGNED,
   INVOICENUMBER BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   FOREIGN KEY(TRANSID)REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE,
   PRIMARY KEY(SHOPID, INVOICENUMBER)
) ENGINE='MyISAM';


CREATE TABLE RETAILADVANCEBILL (
   SHOPID BIGINT UNSIGNED,
   TRANSID BIGINT UNSIGNED,
   ADVANCE_RECEIPT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   FOREIGN KEY(TRANSID)REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE,
   PRIMARY KEY(SHOPID, ADVANCE_RECEIPT_ID)
) ENGINE='MyISAM';


CREATE TABLE RETAILGOLDITEMTRANSACTION(
	TRANSID BIGINT UNSIGNED,
	GOLDTYPE VARCHAR(255) NOT NULL,
	ITEMNAME VARCHAR(255) NOT NULL,
	QUANTITY DECIMAL(4) UNSIGNED,
	PIECEPAIR VARCHAR(255) NOT NULL,
	WEIGHT   DECIMAL(9, 4) UNSIGNED,
	MAKINGCHARGE  DECIMAL(10, 4) UNSIGNED,
	MAKINGCHARGETYPE VARCHAR(8) NOT NULL,
	GOLDRATE DECIMAL(10, 4) UNSIGNED,
	ITEMPRICE DECIMAL(12, 3) UNSIGNED,
	FOREIGN KEY(TRANSID) REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE RETAILSILVERITEMTRANSACTION(
	TRANSID BIGINT UNSIGNED,
	ITEMNAME VARCHAR(255) NOT NULL,
	QUANTITY DECIMAL(4) UNSIGNED,
	PIECEPAIR VARCHAR(255) NOT NULL,
	WEIGHT   DECIMAL(9, 4) UNSIGNED,
	MAKINGCHARGE  DECIMAL(10, 4) UNSIGNED,
	MAKINGCHARGETYPE VARCHAR(8) NOT NULL,
	SILVERRATE DECIMAL(10, 4) UNSIGNED,
	ITEMPRICE DECIMAL(12, 3) UNSIGNED,
	FOREIGN KEY(TRANSID) REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE RETAILDIAMONDITEMTRANSACTION(
	TRANSID BIGINT UNSIGNED,
	ITEMNAME VARCHAR(255) NOT NULL,
	QUANTITY DECIMAL(4) UNSIGNED,
	PIECEPAIR VARCHAR(255) NOT NULL,
	GOLDWEIGHT   DECIMAL(9, 4) UNSIGNED,
	DIAMONDWEIGHT DECIMAL(9, 4) UNSIGNED,
	DIAMONDPIECECOUNT  DECIMAL(4) UNSIGNED,
	CERTIFICATE ENUM('Y', 'N') DEFAULT 'N' NOT NULL,
	ITEMPRICE DECIMAL(12, 3) UNSIGNED,
	FOREIGN KEY(TRANSID) REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE RETAILGENERALITEMTRANSACTION(
	TRANSID BIGINT UNSIGNED,
	ITEMNAME VARCHAR(255) NOT NULL,
	QUANTITY DECIMAL(4) UNSIGNED,
	PIECEPAIR VARCHAR(255) NOT NULL,
	ITEMWEIGHT   DECIMAL(9, 4) UNSIGNED,
	PRICEPERPIECEPAIR DECIMAL(12, 3) UNSIGNED,
	ITEMPRICE DECIMAL(12, 3) UNSIGNED,
	FOREIGN KEY(TRANSID) REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE RETAILTRANSACTIONPRICE(
	TRANSID BIGINT UNSIGNED,
	TOTALITEMSPRICE DECIMAL(12, 3) UNSIGNED NOT NULL,
	DISCOUNT DECIMAL(15, 3) SIGNED ,
	VATPERCENT DECIMAL(12, 3) UNSIGNED ,
	VATONNEWITEMS DECIMAL(12, 3) UNSIGNED,
	OLDPURCHASEPRICE DECIMAL(15, 3) SIGNED,
	NETPAYABLEPRICE DECIMAL(15, 3) SIGNED,
	ADVANCEPAYMENT DECIMAL(15, 3) SIGNED,
	BALANCEAMOUNT DECIMAL(15, 3) SIGNED,
	FOREIGN KEY(TRANSID) REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE RETAILTRANSACTIONPAYMENT(
	TRANSID BIGINT UNSIGNED,
	TOTALCARDPAYMENT DECIMAL(15, 3) UNSIGNED DEFAULT 0.00,
	CASHPAYMENT DECIMAL(15, 3) UNSIGNED DEFAULT 0.00,
	CHEQUEPAYMENT DECIMAL(15, 3) UNSIGNED DEFAULT 0.00,
	NEFTPAYMENT DECIMAL(15, 3) UNSIGNED DEFAULT 0.00,
	RGTSPAYMENT DECIMAL(15, 3) UNSIGNED DEFAULT 0.00,
	FOREIGN KEY(TRANSID) REFERENCES RETAILTRANSACTION(TRANSID) ON DELETE CASCADE
)ENGINE='InnoDB';

CREATE TABLE RETAILGOLDITEM(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	ITEMNAME VARCHAR(255) NOT NULL,
	OWNER ENUM('S', 'U') DEFAULT 'S' NOT NULL,
	QUANTITY SMALLINT NOT NULL DEFAULT 0,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, ITEMNAME)
)ENGINE='InnoDB';

CREATE TABLE RETAILSILVERITEM(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	ITEMNAME VARCHAR(255) NOT NULL,
	OWNER ENUM('S', 'U') DEFAULT 'S' NOT NULL,
	QUANTITY SMALLINT NOT NULL DEFAULT 0,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, ITEMNAME)
)ENGINE='InnoDB';

CREATE TABLE RETAILDIAMONDITEM(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	ITEMNAME VARCHAR(255) NOT NULL,
	OWNER ENUM('S', 'U') DEFAULT 'S' NOT NULL,
	QUANTITY SMALLINT NOT NULL DEFAULT 0,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, ITEMNAME)
)ENGINE='InnoDB';

CREATE TABLE RETAILGENERALITEM(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	ITEMNAME VARCHAR(255) NOT NULL,
	OWNER ENUM('S', 'U') DEFAULT 'S' NOT NULL,
	QUANTITY SMALLINT NOT NULL DEFAULT 0,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, ITEMNAME)
)ENGINE='InnoDB';

CREATE TABLE RETAILSTAFF(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	STAFFNAME VARCHAR(255) NOT NULL,
	OWNER ENUM('S', 'U') DEFAULT 'S' NOT NULL,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, STAFFNAME)
)ENGINE='InnoDB';

CREATE TABLE RETAILSMS(
	SHOPID SMALLINT UNSIGNED NOT NULL,
	SMSUSERID VARCHAR(255) NOT NULL,
	SMSUSERPASSWORD VARCHAR(255) NOT NULL,
	SMSSENDERID VARCHAR(255) NOT NULL,
	SMSGATEWAYURL VARCHAR(255) NOT NULL,
	FOREIGN KEY(SHOPID)REFERENCES SHOP(SHOPID) ON DELETE CASCADE,
	PRIMARY KEY(SHOPID, SMSUSERID)
)ENGINE='InnoDB';