DROP PROCEDURE IF EXISTS CUSTOMTRANSACTIONSEARCH;
DELIMITER $$
CREATE PROCEDURE `CUSTOMTRANSACTIONSEARCH`(
	SHOPID SMALLINT UNSIGNED,
	BILLTYPE1 VARCHAR(1),
	BILLTYPE2 VARCHAR(1),
	TRANSSTATUS1 VARCHAR(1),		
	TRANSSTATUS2 VARCHAR(1),		
	STARTDATE DATETIME,
	ENDDATE DATETIME
)
BEGIN
	DECLARE v_finished INTEGER DEFAULT 0;
	DECLARE v_transId  BIGINT UNSIGNED;
	
	DECLARE transId_cursor CURSOR FOR  SELECT TRANSID FROM TRANSANCTION_ID_HOLDER;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_finished = 1;

CREATE TEMPORARY TABLE TRANSANCTION_SEARCH_RESULT(
	TRANSDATE DATETIME,
	TRANSID BIGINT UNSIGNED,
	BILLTYPE ENUM('I', 'E'),
	TRANSACTIONSTATUS ENUM('A', 'I'),
	GOLDITEMS VARCHAR(2048) DEFAULT '',
	SILVERITEMS VARCHAR(2048) DEFAULT '',
	DIAMONDITEMS VARCHAR(2048) DEFAULT '',
	GENERALITEMS VARCHAR(2048) DEFAULT '',
	CUSTOMERNAME VARCHAR(512),
	CONTACTNUMBER VARCHAR(255),
	EMAILID VARCHAR(255),
	ADDRESS VARCHAR(1024),
	TOTALITEMSPRICE DECIMAL(12, 3) UNSIGNED
);
CREATE TEMPORARY TABLE TRANSANCTION_ID_HOLDER(
	TRANSID BIGINT UNSIGNED
);
INSERT INTO TRANSANCTION_SEARCH_RESULT(TRANSDATE, TRANSID, BILLTYPE, TRANSACTIONSTATUS, CUSTOMERNAME, CONTACTNUMBER, EMAILID, ADDRESS, TOTALITEMSPRICE)
	SELECT 	RT.TRANSDATE,
			RT.TRANSID,
			RT.BILLTYPE,
			RT.TRANSACTIONSTATUS,
			CONCAT(RC.FIRSTNAME, ' ', RC.LASTNAME) CUSTOMERNAME,
			RC.CONTACTNUMBER,
			RC.EMAILID,
			CONCAT(RC.STREETADDRESS1, ' ', RC.STREETADDRESS2, ' ', RC.CITY , ' ', RC.STATE, ' ', RC.ZIPCODE, ' ', RC.COUNTRY) ADDRESS,
			RP.TOTALITEMSPRICE
			FROM SHOP S, RETAILTRANSACTION RT, RETAILCUSTOMER RC, RETAILTRANSACTIONPRICE RP
			WHERE S.SHOPID = RT.SHOPID
			AND RC.TRANSID = RT.TRANSID
			AND RP.TRANSID = RT.TRANSID
			AND S.SHOPID = SHOPID
			AND RT.BILLTYPE in (BILLTYPE1, BILLTYPE2)
			AND RT.TRANSACTIONSTATUS in(TRANSSTATUS1, TRANSSTATUS2)
			AND CAST(RT.TRANSDATE AS DATE) BETWEEN CAST(STARTDATE AS DATE) AND CAST(ENDDATE AS DATE)
			ORDER BY RT.TRANSDATE DESC;
INSERT INTO TRANSANCTION_ID_HOLDER(TRANSID) SELECT TRANSID FROM TRANSANCTION_SEARCH_RESULT;
CREATE TEMPORARY TABLE ITEM_TABLE(
	ITEMNAME VARCHAR(255) DEFAULT '',
	QUANTITY DECIMAL(4) UNSIGNED,
	PIECEPAIR VARCHAR(8) DEFAULT ''
);
OPEN transId_cursor;
    get_transId: LOOP
	FETCH transId_cursor INTO v_transId;
	IF v_finished = 1 THEN 
	 LEAVE get_transId;
	END IF;
	BLOCK2: BEGIN
		DECLARE v_finished_inner INTEGER DEFAULT 0;
		DECLARE itemname_inner  VARCHAR(255);
		DECLARE quantity_inner DECIMAL(4);
		DECLARE piecepair_inner VARCHAR(8);
		DECLARE itemnamelist VARCHAR(2048) DEFAULT NULL;
		DECLARE item_cursor CURSOR FOR  SELECT ITEMNAME, QUANTITY, PIECEPAIR FROM ITEM_TABLE;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_finished_inner = 1;
		SET itemnamelist = NULL;
		INSERT INTO ITEM_TABLE(ITEMNAME, QUANTITY, PIECEPAIR) SELECT ITEMNAME, QUANTITY, PIECEPAIR FROM RETAILGOLDITEMTRANSACTION WHERE TRANSID = v_transId;
		OPEN item_cursor;
			 get_item: LOOP
				FETCH item_cursor INTO itemname_inner, quantity_inner, piecepair_inner;
				IF v_finished_inner = 1 THEN 
					LEAVE get_item;
				END IF;
				SET itemnamelist = CONCAT_WS(',', CONCAT(itemname_inner, '(', quantity_inner, ' ', piecepair_inner, ')'), itemnamelist);
			 END LOOP get_item;
		    UPDATE TRANSANCTION_SEARCH_RESULT SET GOLDITEMS = itemnamelist WHERE TRANSID = v_transId;
		CLOSE item_cursor;
		TRUNCATE ITEM_TABLE;
		
		SET v_finished_inner = 0;
		SET itemnamelist = NULL;
		INSERT INTO ITEM_TABLE(ITEMNAME, QUANTITY, PIECEPAIR) SELECT ITEMNAME, QUANTITY, PIECEPAIR FROM RETAILSILVERITEMTRANSACTION WHERE TRANSID = v_transId;
		OPEN item_cursor;
			 get_item: LOOP
				FETCH item_cursor INTO itemname_inner, quantity_inner, piecepair_inner;
				IF v_finished_inner = 1 THEN 
					LEAVE get_item;
				END IF;
				SET itemnamelist = CONCAT_WS(',', CONCAT(itemname_inner, '(', quantity_inner, ' ', piecepair_inner, ')'), itemnamelist);
			 END LOOP get_item;
			 UPDATE TRANSANCTION_SEARCH_RESULT SET SILVERITEMS = itemnamelist WHERE TRANSID = v_transId;
		CLOSE item_cursor;
		TRUNCATE ITEM_TABLE;
		
		SET v_finished_inner = 0;
		SET itemnamelist = NULL;
		INSERT INTO ITEM_TABLE(ITEMNAME, QUANTITY, PIECEPAIR) SELECT ITEMNAME, QUANTITY, PIECEPAIR FROM RETAILDIAMONDITEMTRANSACTION WHERE TRANSID = v_transId;
		OPEN item_cursor;
			 get_item: LOOP
				FETCH item_cursor INTO itemname_inner, quantity_inner, piecepair_inner;
				IF v_finished_inner = 1 THEN 
					LEAVE get_item;
				END IF;
				SET itemnamelist = CONCAT_WS(',', CONCAT(itemname_inner, '(', quantity_inner, ' ', piecepair_inner, ')'), itemnamelist);
			 END LOOP get_item;
			 UPDATE TRANSANCTION_SEARCH_RESULT SET DIAMONDITEMS = itemnamelist WHERE TRANSID = v_transId;
		CLOSE item_cursor;
		TRUNCATE ITEM_TABLE;
		
		SET v_finished_inner = 0;
		SET itemnamelist = NULL;
		INSERT INTO ITEM_TABLE(ITEMNAME, QUANTITY, PIECEPAIR) SELECT ITEMNAME, QUANTITY, PIECEPAIR FROM RETAILGENERALITEMTRANSACTION WHERE TRANSID = v_transId;
		OPEN item_cursor;
			 get_item: LOOP
				FETCH item_cursor INTO itemname_inner, quantity_inner, piecepair_inner;
				IF v_finished_inner = 1 THEN 
					LEAVE get_item;
				END IF;
				SET itemnamelist = CONCAT_WS(',', CONCAT(itemname_inner, '(', quantity_inner, ' ', piecepair_inner, ')'), itemnamelist);
			 END LOOP get_item;
			 UPDATE TRANSANCTION_SEARCH_RESULT SET GENERALITEMS = itemnamelist WHERE TRANSID = v_transId;
		CLOSE item_cursor;
		TRUNCATE ITEM_TABLE;
	END BLOCK2;
END LOOP get_transId;
CLOSE transId_cursor;
SELECT * FROM TRANSANCTION_SEARCH_RESULT;
DROP TEMPORARY TABLE TRANSANCTION_SEARCH_RESULT;
DROP TEMPORARY TABLE TRANSANCTION_ID_HOLDER;
DROP TEMPORARY TABLE ITEM_TABLE;
END$$
